import os

p = '/Users/julien/Documents/IPvicious/internal/protocol/protocol_test.go'
lines = [
    '// Package protocol: round-trip tests for Encode / Decode with compression.\n',
    'package protocol\n',
    '\n',
    'import (\n',
    '\t"bytes"\n',
    '\t"strings"\n',
    '\t"testing"\n',
    ')\n',
    '\n',
    'func makeFrame(typ byte, streamID, seqNo uint32, data []byte) *Frame {\n',
    '\treturn &Frame{Type: typ, StreamID: streamID, SeqNo: seqNo, Data: data}\n',
    '}\n',
    '\n',
    'func TestRoundTrip(t *testing.T) {\n',
    '\tcases := []struct {\n',
    '\t\tname string\n',
    '\t\tdata []byte\n',
    '\t}{\n',
    '\t\t{name: "empty", data: nil},\n',
    '\t\t{name: "small_below_threshold", data: []byte("hello")},\n',
    '\t\t{\n',
    '\t\t\tname: "text_compresses_well",\n',
    '\t\t\tdata: []byte(strings.Repeat("GET / HTTP/1.1\\r\\nHost: target\\r\\n\\r\\n", 20)),\n',
    '\t\t},\n',
    '\t\t{\n',
    '\t\t\tname: "binary_incompressible",\n',
    '\t\t\tdata: func() []byte {\n',
    '\t\t\t\tb := make([]byte, 512)\n',
    '\t\t\t\tfor i := range b {\n',
    '\t\t\t\t\tb[i] = byte(i*31 + 7)\n',
    '\t\t\t\t}\n',
    '\t\t\t\treturn b\n',
    '\t\t\t}(),\n',
    '\t\t},\n',
    '\t\t{name: "max_text_payload", data: []byte(strings.Repeat("A", MAX_DATA))},\n',
    '\t}\n',
    '\tfor _, tc := range cases {\n',
    '\t\tt.Run(tc.name, func(t *testing.T) {\n',
    '\t\t\toriginal := makeFrame(TypeData, 42, 7, tc.data)\n',
    '\t\t\tencoded, err := Encode(original)\n',
    '\t\t\tif err != nil {\n',
    '\t\t\t\tt.Fatalf("Encode: %v", err)\n',
    '\t\t\t}\n',
    '\t\t\tif len(encoded) != PAYLOAD_SIZE {\n',
    '\t\t\t\tt.Fatalf("Encode: want %d bytes, got %d", PAYLOAD_SIZE, len(encoded))\n',
    '\t\t\t}\n',
    '\t\t\tdecoded, err := Decode(encoded)\n',
    '\t\t\tif err != nil {\n',
    '\t\t\t\tt.Fatalf("Decode: %v", err)\n',
    '\t\t\t}\n',
    '\t\t\tif decoded.Type != original.Type {\n',
    '\t\t\t\tt.Errorf("Type mismatch")\n',
    '\t\t\t}\n',
    '\t\t\tif decoded.StreamID != original.StreamID {\n',
    '\t\t\t\tt.Errorf("StreamID mismatch")\n',
    '\t\t\t}\n',
    '\t\t\tif decoded.SeqNo != original.SeqNo {\n',
    '\t\t\t\tt.Errorf("SeqNo mismatch")\n',
    '\t\t\t}\n',
    '\t\t\tif !bytes.Equal(decoded.Data, original.Data) {\n',
    '\t\t\t\tt.Errorf("Data mismatch: want %d bytes, got %d bytes",\n',
    '\t\t\t\t\tlen(original.Data), len(decoded.Data))\n',
    '\t\t\t}\n',
    '\t\t\tif decoded.Flags&FlagCompressed != 0 {\n',
    '\t\t\t\tt.Errorf("FlagCompressed not cleared by Decode")\n',
    '\t\t\t}\n',
    '\t\t})\n',
    '\t}\n',
    '}\n',
    '\n',
    'func TestCompressionFires(t *testing.T) {\n',
    '\tpayload := []byte(strings.Repeat("AAAAAAAAAA", 50))\n',
    '\tencoded, err := Encode(makeFrame(TypeData, 1, 1, payload))\n',
    '\tif err != nil {\n',
    '\t\tt.Fatalf("Encode: %v", err)\n',
    '\t}\n',
    '\tif encoded[9]&FlagCompressed == 0 {\n',
    '\t\tt.Error("FlagCompressed expected for compressible payload")\n',
    '\t}\n',
    '\tdecoded, err := Decode(encoded)\n',
    '\tif err != nil {\n',
    '\t\tt.Fatalf("Decode: %v", err)\n',
    '\t}\n',
    '\tif !bytes.Equal(decoded.Data, payload) {\n',
    '\t\tt.Error("round-trip data mismatch after compression")\n',
    '\t}\n',
    '}\n',
    '\n',
    'func TestIncompressibleNotExpanded(t *testing.T) {\n',
    '\tpayload := make([]byte, 200)\n',
    '\tfor i := range payload {\n',
    '\t\tpayload[i] = byte(i)\n',
    '\t}\n',
    '\tencoded, err := Encode(makeFrame(TypeCmd, 0, 0, payload))\n',
    '\tif err != nil {\n',
    '\t\tt.Fatalf("Encode: %v", err)\n',
    '\t}\n',
    '\tdecoded, err := Decode(encoded)\n',
    '\tif err != nil {\n',
    '\t\tt.Fatalf("Decode: %v", err)\n',
    '\t}\n',
    '\tif !bytes.Equal(decoded.Data, payload) {\n',
    '\t\tt.Error("data mismatch for incompressible payload")\n',
    '\t}\n',
    '}\n',
    '\n',
    'func TestBadMagic(t *testing.T) {\n',
    '\tbuf := make([]byte, PAYLOAD_SIZE)\n',
    '\tbuf[0] = 0xFF\n',
    '\t_, err := Decode(buf)\n',
    '\tif err != ErrBadMagic {\n',
    '\t\tt.Errorf("expected ErrBadMagic, got %v", err)\n',
    '\t}\n',
    '}\n',
]
with open(p, 'w') as f:
    f.writelines(lines)
print('written', len(lines), 'lines')
